name: Rendering Editorial Communication Material
on:
  push:
    paths:
       - editorial-communication/**
       - .github/workflows/editorial-comm-render-build-deploy.yaml
  pull_request:
    paths:
       - editorial-communication/**  

jobs:
  editorial-communication-rendering:
    name: Render the editorial communication material
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: editorial-communication
        
    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@v2

      - name: 💻 Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: 💾 Cache R packages
        uses: actions/cache@v2 # Must be v2 so it accepts the GITHUB_REF from the repository_dispatch
        with:
          path: ${{ env.R_LIBS_USER }}
          key:  r-${{ hashFiles('DESCRIPTION') }}

      - name: 💻 Install pandoc and pandoc citeproc
        uses: r-lib/actions/setup-pandoc@v1
    
      - name: 💻 Install R packages and dependencies if needed
        run: |
          Rscript -e 'list.of.packages <- c("rmarkdown", "bookdown", "formatR"); 
          new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]; 
          if(length(new.packages) > 0) {  
          install.packages(new.packages, dependencies = TRUE)   
          print(paste0("The following package was installed:", new.packages))} else 
          if(length(new.packages) == 0) {
          print("All packages have been previously installed and fetched from cache.")}'
          
      - name: 🧶 Render
        run: Rscript -e 'rmarkdown::render("cover-letter-submission.Rmd")'
        
      - name: 🧶 Render
        uses: quarto-dev/quarto-actions/render@v2
        with: 
          to: html
          path: "response-to-the-reviewers.Qmd"
        
      - name: 🔺 Upload artifact containing the letter
        uses: actions/upload-artifact@v1
        with:
          name: editorial-communication
          path: editorial-communication/        
        
        
  checkout-and-deploy-editorial-communication:
   name: Checkout and deploy the editorial communication material within the gh-pages repository
   runs-on: ubuntu-latest
   needs: editorial-communication-rendering
   
   steps:
      - name: 🛎️ Checkout again
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          
      - name: 🔻 Download artifact containing the book
        uses: actions/download-artifact@v1
        with:
         # Artifact name
         name: editorial-communication # optional
         # Destination path
         path: editorial-communication/ # optional

      - name: 💎 Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: editorial-communication/
          target-folder: editorial-communication # The folder the action should deploy
          clean: true
   
